version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - mosq_data:/mosquitto/data
      - mosq_log:/mosquitto/log
    restart: unless-stopped

  broker-beacon:
    image: python:3.11-slim
    container_name: broker-beacon
    restart: unless-stopped
    ports:
      - "18830:18830/udp"          # Map UDP port for beacon broadcasts
    environment:
      - PYTHONUNBUFFERED=1
      - BEACON_IP=192.168.1.7      # ⚠️ CHANGE THIS to your WiFi IP address!
    volumes:
      - ./beacon.py:/app/beacon.py:ro
    command: ["python", "/app/beacon.py"]

  face-service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: face-service
    devices:
      - "/dev/video0:/dev/video0"
    group_add:
      - "video"
    environment:
      - TZ=Etc/UTC
    ports:
      - "8000:8000"
    volumes:
      - ./persons:/data/persons:ro
      - ./captures:/data/caps
    depends_on:
      - mosquitto
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    environment:
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_DEFAULT_LOCALE=en
      - GENERIC_TIMEZONE=Etc/UTC
      - TZ=Etc/UTC
      - N8N_ENCRYPTION_KEY=my_fixed_key_here
      - N8N_EXECUTIONS_DATA_PRUNE=true
      - N8N_EXECUTIONS_DATA_MAX_AGE=168  # 7 days
      - N8N_EXECUTIONS_PRUNE_INTERVAL=60 # prune every hour
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  mosq_data:
  mosq_log:
